# Exercise 2 - Classification

Suppose we want to classify some data (4 samples) into 3 distinct classes: 0, 1, and 2.
We have set up a network with a pre-activation output z in the last layer.
Applying softmax will give the final model output.
input X ---> some network --> z --> y_model = softmax(z)

We quantify the agreement between truth (y) and model using categorical cross-entropy.

```J = - sum_i (y_i * log(y_model(x_i))```

In the following you are to implement softmax and categorical cross-entropy and evaluate them values given the values for z.


In [1]:
from __future__ import print_function
from comet_ml import Experiment
import numpy as np
import tensorflow as tf

In [2]:
experiment = Experiment(
    api_key="EnterYourAPIKey",
    project_name="exercise2",
    workspace="EnterGroupWorkspaceHere",
)

COMET WARNING: As you are running in a Jupyter environment, you will need to call `experiment.end()` when finished to ensure all metrics and code are logged before exiting.
COMET ERROR: The given API key EnterYourAPIKey is invalid on www.comet.com, please check it against the dashboard. Your experiment will not be logged 
For more details, please refer to: https://www.comet.com/docs/v2/api-and-sdk/python-sdk/warnings-errors/
COMET ERROR: The given API key EnterYourAPIKey is invalid on www.comet.com, please check it against the dashboard. Your experiment will not be logged 
For more details, please refer to: https://www.comet.com/docs/v2/api-and-sdk/python-sdk/warnings-errors/


In [3]:
# Data: 4 samples with the following class labels (input features X irrelevant here)
y_cl = np.array([0, 0, 2, 1])

# output of the last network layer before applying softmax
z = np.array([[4, 5, 1], [-1, -2, -3], [0.1, 0.2, 0.3], [-1, 17, 1]]).astype(np.float32)


# TensorFlow implementation as reference. Make sure you get the same results!
print("\nTensorFlow 2.0 ------------------------------ ")


TensorFlow 2.0 ------------------------------ 


In [4]:
def crossentropy(x, y):
    return tf.reduce_mean(-tf.reduce_sum(y * tf.math.log(x), axis=1))


y = tf.one_hot(y_cl, 3)
y_model = tf.nn.softmax(z)

print("softmax(z)")
print(y_model)
print("cross entropy", crossentropy(y_model, y))

softmax(z)
tf.Tensor(
[[2.6538792e-01 7.2139919e-01 1.3212888e-02]
 [6.6524094e-01 2.4472848e-01 9.0030573e-02]
 [3.0060959e-01 3.3222499e-01 3.6716542e-01]
 [1.5229979e-08 9.9999988e-01 1.1253516e-07]], shape=(4, 3), dtype=float32)
cross entropy tf.Tensor(0.6840279, shape=(), dtype=float32)


In [5]:
print("\nMy solution ------------------------------ ")
# 1) Write a function that turns any class labels y_cl into one-hot encodings y.
#    0 --> (1, 0, 0)
#    1 --> (0, 1, 0)
#    2 --> (0, 0, 1)
#    Make sure that np.shape(y) = (4, 3) for np.shape(y_cl) = (4).


def to_onehot(y_cl, num_classes):
    y = np.zeros((len(y_cl), num_classes))
    return y


My solution ------------------------------ 
